# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       brcm-patchram-plus

# >> macros
# << macros

Summary:    Tool to patch Broadcom Bluetooth chips.
Version:    0.1.1
Release:    1.1.1
Group:      System/Base
License:    Apache
Source0:    brcm-patchram-plus.c
Source100:  brcm-patchram-plus.yaml
Requires:   glibc
BuildRequires:  gcc
BuildRequires:  glibc

%description
This program downloads a patchram files in the HCD format to Broadcom Bluetooth based silicon and combo chips and and other utility functions.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
gcc -o brcm_patchram_plus brcm_patchram_plus.c
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}/%{_sbindir}
cp brcm_patchram_plus %{buildroot}/%{_sbindir}/brcm_patchram_plus
chmod 755 %{buildroot}/%{_sbindir}/brcm_patchram_plus
# << install pre

# >> install post
# << install post


%files
%defattr(-,root,root,-)
%{_sbindir}/brcm_patchram_plus
# >> files
# << files
%changelog
* Fri Feb  8 2013 Ruediger Gad <r.c.g@gmx.de> - 0.1.1
- Update to latest Ubuntu version.
* Fri Dec 28 2012 Ruediger Gad <r.c.g@gmx.de> - 0.1
- First version for Mer.
